services:
  db:
    # Do not publish MySQL port in production
    ports: []
    restart: unless-stopped

  api:
    env_file:
      - ${HOME}/.env.backend.production
    command: >
      sh -c "npx sequelize db:migrate --debug && npm run start"
    ports:
      - "3000:3000"
    restart: unless-stopped
