version: "3.8"

services:
  db:
    # Expose DB port in staging if needed
    ports:
      - "3306:3306"
    restart: unless-stopped

  api:
    env_file:
      - ${HOME}/.env.backend.staging
    ports:
      - "3001:3000"
    restart: unless-stopped
